1. Create a class Employee and then do the following:

Create a data member to count the number of Employees

Create a constructor to initialize name, family, salary, department

Create a function to average salary

Create a Fulltime Employee class and it should inherit the properties of Employee class

Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [2]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Aishwarya", "Pasumarthy", 1500000, "Devops engineer")
employee2 = Employee("Alekya", "Pasumarthy", 60000, "Developer")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Mani", "pasumarthy", 90000, "IT")
fulltime_employee2 = FulltimeEmployee("Bhaskar", "pasumarthy", 50000, "Software engineer")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 390000.0
Average Salary for Fulltime Employees: 35000.0


Using NumPy:

create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)
Note: (you can NOT implement it via for loop)

In [3]:

# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [11.11375983 11.81788486 14.57452404  1.07332195 16.62057283 10.13470148
 16.63856411  3.36745458 17.83029932  6.64950703 11.09405334 14.55147369
  2.69178142 18.17075576 15.04057404 13.16847636 12.40319517  5.96084351
  1.35718389  9.14222417]


In [4]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[11.11375983 11.81788486 14.57452404  1.07332195 16.62057283]
 [10.13470148 16.63856411  3.36745458 17.83029932  6.64950703]
 [11.09405334 14.55147369  2.69178142 18.17075576 15.04057404]
 [13.16847636 12.40319517  5.96084351  1.35718389  9.14222417]]


In [5]:

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[11.11375983 11.81788486 14.57452404  1.07332195  0.        ]
 [10.13470148 16.63856411  3.36745458  0.          6.64950703]
 [11.09405334 14.55147369  2.69178142  0.         15.04057404]
 [ 0.         12.40319517  5.96084351  1.35718389  9.14222417]]
